site_name: WEC-Grid
site_description: Integrating Wave Energy Converter Models into Power System Simulations
repo_url: https://github.com/acep-uaf/WEC-Grid
theme:
  name: ivory
  logo: assets/logo.png     # Main site logo
  nav_style: dark

plugins:
  - search
  # - plantuml:
  #     puml_url: https://www.plantuml.com/plantuml/
  #     num_workers: 8

  - mkapi:
      src_dirs: [src]
      filters: [
        "!^_",        # Exclude private methods
        "!^test_",    # Exclude test functions
      ]
  - mkdocs-jupyter:
      include: ["*.ipynb"] 
      execute: false
      include_source: True
nav:
  - Getting Started:
      - Introduction: index.md
      - Software Design: design.md
      - Installation: install.md
  - WECGrid:
    - Engine: wecgrid/engine.md
    - Modelers:
      - Power System:
        - Base: wecgrid/base.md
        - Grid State: wecgrid/grid.md
        - PSS/E: wecgrid/psse.md
        - PyPSA: wecgrid/pypsa.md
      - WEC-Sim:
        - Runner: wecgrid/wecsim.md
    - WEC:
      - WEC Farm: wecgrid/wec_farm.md
      - WEC Device: wecgrid/wec_device.md
    - Util:
      - Database: wecgrid/database.md
      - Time: wecgrid/time.md
      - Plot: wecgrid/plot.md
  - Examples & Data:
    - Jupyter notebooks:
      - Example 1: examples/jupyter_notebooks/example1.ipynb
      - Example 2: examples/jupyter_notebooks/example2.ipynb
      - Example 3: examples/jupyter_notebooks/example3.ipynb
      - Example 4 : examples/jupyter_notebooks/example4.ipynb
    - Data:
      - Grid Models: examples/data/grid-models.md
      - WEC Models: examples/data/wec-models.md
      - Database: examples/data/database.md
  - Reference:
      - API Reference: reference/api.md
      - Troubleshooting: reference/troubleshooting.md
      - Citation: reference/citation.md
