site_name: WecGrid Documentation
theme:
  name: material
nav:
  - Home: index.md
  - API:
      - PSSe: api/PSSe.md
      - Utilities: api/utilities.md
      - Wec: api/wec.md
      - pyPSA: api/pyPSA.md
      - cec: api/cec.md
      - Database: api/database.md
      - WecGrid: api/WecGrid.md # core.py 
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
