[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "marinegrid"
version = "2.0.0"
description = "Marine-Grid: A tool for integrating marine renewable energy models into power system simulations"
readme = "README.md"
requires-python = ">=3.7"
authors = [{name = "Alexander Barajas-Ritchie", email = "barajale@oregonstate.edu"}]
license = {file = "LICENSE"}
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "pypsa",
    "grg-pssedata",
    "networkx",
    "pyomo",
    "tqdm",
    "jupyter",
    "mkdocstrings-python"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/acep-uaf/Marine-Grid"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
marinegrid = [
    "util/*.json",
    "modeler/wecsim/*.json",
]
