name: Build and Deploy Docs
on:
  push:
    branches:
      - main
      - softwareX
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Sphinx
        run: pip install sphinx
      - name: Build docs
        run: sphinx-build -b html docs/ build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/